<?php
/*
 * Turiknox_Facebookpixel

 * @category   Turiknox
 * @package    Turiknox_Facebookpixel
 * @copyright  Copyright (c) 2017 Turiknox
 * @license    https://github.com/Turiknox/magento-facebook-pixel/blob/master/LICENSE.md
 * @version    1.1.1
 */
?>
<?php if ($this->isEventAllowed('add_to_cart')): ?>
    <?php if ($products = Mage::getSingleton('core/session')->getData('fb_addtocart')): ?>
        <?php Mage::getSingleton('core/session')->unsetData('fb_addtocart'); ?>
        <script type="text/javascript">
            fbq(
                'track', 'AddToCart',
                {
                    'content_type': '<?php echo $products['content_type']; ?>',
                    'content_ids': ['<?php echo $this->escapeHtml($products['content_ids']); ?>'],
                    'content_name': '<?php echo $this->escapeHtml($products['content_name']); ?>',
                    'value': <?php echo number_format($products['value'],2); ?>,
                    'currency': '<?php echo $products['currency']; ?>',
                    'product_catalog_id': <?php echo $this->escapeHtml($this->getProductCatalogId()); ?>
                }
            );
        </script>
    <?php endif; ?>
<?php endif; ?>
