<?php
/*
 * Turiknox_Facebookpixel

 * @category   Turiknox
 * @package    Turiknox_Facebookpixel
 * @copyright  Copyright (c) 2017 Turiknox
 * @license    https://github.com/Turiknox/magento-facebook-pixel/blob/master/LICENSE.md
 * @version    1.1.1
 */
?>
<?php if ($this->isEventAllowed('search')): ?>
    <script>
        fbq(
            'track', 'Search',
            {
                'search_string': "<?php echo $this->escapeHtml($this->getSearchQuery()); ?>"
            }
        );
    </script>
<?php endif; ?>